### ISSUE TITLE
Lava/Water wont flow inside claims

### ISSUE THREAD

**Issue by GetSplitBro** [Aquerr/EagleFactions#105]
## Environment

* **Sponge Version:** <Not Sure>

* **Plugin Version:** <Not Sure>

## What happens?

<Lava/water wont flow and auto cactus farms where the cactus is supposed to grow then fall into hoppers isnt working, all because of the chunks not updating under the Eagle Factions plugin claims, warzone, or safezone.

## Expected result

<Water/lava should flow, and cactus should break when a block is placed next to it>

## More information

<This only happens inside claims>

**Comment by Aquerr** [comment]
Plugin and Sponge versions are **required** when submitting an issue. If not provided then issue will be **rejected**.

Also, **don’t** place text between **<** and **>** because it won’t be visible. It is meant to put your text instead of these symbols as they are used mainly to represent a placeholder.

Furthermore, given information sounds like something that **has been fixed in recent dev version and currently awaits release**.
