### ISSUE TITLE
/f attack timer still ticks if attacking player died on chunk and didn't respawn

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#125]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.2.2

* **Plugin Version:** EagleFactions-1.12.2-v0.15.2

## What happens?

I (as admin) set the time for /f attack command at 100 secs. 
I used /f attack on the enemy's claim/chunk, the timer in chat appeared, and then I died on that chunk and didn't press the respawn button. The timer was still ticking for me, and at the end the enemy claim was destroyed.

## Expected result

Timer should not tick if attacking player(s) died and didn't respawn.

**Comment by Aquerr** [comment]
@Faelris Thanks for reporting the issue! It is now fixed in dev branch. It will be ready to use in next version. However, I don't have ETA yet. If you want to grab dev version, use this [link](https://jenkins.bartlomiejstepien.pl/job/EagleFactions-dev-build/360/artifact/build/libs/EagleFactions-0.15.2_360-SNAPSHOT.jar). Cheers!
