### ISSUE TITLE
Feature request: /f claim outpost

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#127]
**Is your feature request related to a problem? Please describe.**
Hi! Not so much of a problem, on my server there are many scattered (not connected) claims of 1 or 2 chunks (with config setting connected-claims=false).
It's not a new idea, but the possibility to create outposts (with config setting connected-claims=true) will be a solution for this and a good addition for this great plugin! :)

**Describe the solution you'd like**
When config setting connected-claims=true is set, there's an opportunity to create an outpost (a claim) somewhere else from your main faction claim - you need at least X (configurable) power to do that and the amount of "outposts" for one faction is limited. For example, for every 10 (configurable) people, a faction gains a possibility to claim one outpost.

**Describe alternatives you've considered**

**Additional context**
Maybe some kind of configurable minimum distance between the main faction claim and the outpost.

**Comment by Aquerr** [comment]
Hello! Thank you for submitting your feature request.

I like this idea! 💪 It will be added to my TO DO list. Cheers! 👊

**Comment by Aquerr** [comment]
As because I am cleaning all issues now and I has been some time since this issue got opened, I will be closing it.
Also, this feature request is still in my TO DO list (I just had no time implementing it. Also, still thinking how plugin should behave when we switch connected claims to false after creating outposts) but feel free to reopen this issue or make a new one if you see such need.
