### ISSUE TITLE
Mob spawning / block placing issue

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#132]
## Environment

* **Sponge Version:** 
spongeforge-1.12.2-2838-7.3.0
* **Plugin Version:** 
EagleFactions-1.12.2-v0.15.3

## What happens?

It appears rarely, but I checked all the other possibilities (and plugins w/ configurations also). I wiped my first server map with such problem, but it also appeared on the second and the third one. 
When I set the (spawn-hostile-mobs-in-factions-territory=) to false, it also prevents some mobs to spawn (horses, squids, dogs for example), and also the main issue - you can't place blocks where "the invisible mobs" spawn. I mean, mobs appear to spawn, but turn invisible, preventing placing blocks on the spot where they spawned. 
At first, I thought that it was a sponge issue (maybe it still is), but when I changed this setting (spawn-hostile-mobs-in-factions-territory=) to true and restarted the server, all "invisible mobs" appear visible, died, and I was actually able to place blocks there.
Also, no info on this appeared on the console.
MCedit helped with this issue also, but the problem appeared again, sometimes in the same chunks.

## Expected result

Mob spawning prevention should work as intended.
Maybe a custom configuration for each faction for mob spawning prevention might work, or custom configuration for each type of mob (or even both).
"/f flag"-like configuration system?

**Comment by Aquerr** [comment]
Thanks for your report. I will look at this asap. Also, your suggestion for a new flag is nice.

**Comment by Aquerr** [comment]
I was looking at the code and it looks like that:
1. Eagle Factions listens for EntitySpawnEvent.
2. If the entity is hostile then we are prefroming some operations. Horses do not count as Hostile.
3. If we detect that mob should not be spawned, either due to configuration or protected territory then we are cancelling the spawn event which should result in mob being not spawned.

So it is hard to tell for me why are your mobs invisible.
