### ISSUE TITLE
Maxpower not updating for existing players

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#134]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.3.0

* **Plugin Version:** EagleFactions-1.12.2-v0.15.4

## What happens?

When updating max-power in config, it only applies for new players. Existing ones have the same max-power as before.

## Expected result

Existing players also receiving max-power updated value.

**Comment by Aquerr** [comment]
This will not be changed as it works as intended. The config should apply only for new players. If you want to modify player maxpower afterwards, you have to use a command.

The reason why it will not be changed is that the player may already have maxpower set to some custom value. Changing the maxpower inside the config file would then overwrite that custom maxpower value. And by that, giving someone custom maxpower by the command would always be temporary.

A workaround is to update maxpower for each (not new) player manually or delete the player from your storage so that its data will be generated again.

I know that EF has only a command for editing the maxpower for just one player which in such situations - where you have a lot of players on your server - is painful. That is why I will be adding a new command that will allow admins to set/update maxpower for all players.

**Comment by Faelris** [comment]
Yay! Understood! Thank you very much! :)
