### ISSUE TITLE
Eaglefactions overwriting nucleus/luckperms prefixes and nicknames

### ISSUE THREAD

**Issue by TomTheHero** [Aquerr/EagleFactions#44]
I'm running the latest version of eaglefactions for api 5 on sponge version 5.2.0-BETA-2790(the newest one causes issues with alot of plugins) for 1.10.2 and eaglefactions is overwriting all nicknames and prefixes even if nucleus is set to overwrite them

**Comment by Aquerr** [comment]
Hmmm... I remember that I fixed something like this (I think there was a problem with prefixes from LuckPerms) in the latest release.

Could you please send me some examples for when is this happening?
It would be great to know what other plugins for chat you are using and how did you configurate them so that it is not working properly.

I will do my best to fix this until the next release. :)

**Comment by TomTheHero** [comment]
I'm using nucleus controls the chat and luckperms overwrites the chat by adding the prefixes to it but whenever someone is part of a faction everything gets overwritten by eaglefactions

**Comment by TomTheHero** [comment]
Note that 0.9.7 is set as the current version on your spongeforums page while 0.9.8 has been released for like 20 days already so you might want to fix that and i will try 0.9.8 tomorrow to see if that perhaps fixes my issues.

**Comment by Aquerr** [comment]
Damn... Looks like I forgot about changing it to 0.9.8

Thanks for telling me about it.

**Comment by Aquerr** [comment]
@TomTheHero Any status on this? Is it still not working?

**Comment by TomTheHero** [comment]
Updating to 0.9.8 fixed it

**Comment by Aquerr** [comment]
Good to hear :) I am closing this issue then 😄
