### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TomTheHero** [Aquerr/EagleFactions#63]
I suggest a config that allows all commands to be blocked whenever a player is in combat so they cannot teleport away while in combat.

**Comment by TomTheHero** [comment]
And i also just noticed that you made a little mistake in your config here: http://prntscr.com/j0s779

**Comment by Aquerr** [comment]
Ah, right, my fault. It should be „maximum” instead of „minimum”.

___

disable-block-destroy=false

above config node means that every explosion (TNT, creeper, enderman-grief, etc.) will be blocked in the faction. So yes, if the faction is under attack, this node still blocks every explosion.

___
**Config for disabling commands while being in combat**

So you mean that there should be a config node e.g. **disable-commands-while-in-pvp** that will disable all commands if player is in pvp?

Sounds good for me. Just tell me if I undrestood everything correctly. :)

**Comment by TomTheHero** [comment]
Yep 🍪

**Comment by Aquerr** [comment]
Alright, I will add this node then 😄

**Comment by Aquerr** [comment]
@TomTheHero I am currently working on a config for **disabling commands while being in combat**.

I am wondering if that node should block all commands (from Eagle Factions) or only Home Command. I can't see any reason why other commands should be blocked except **/f home**.

What do you think?

**Comment by Aquerr** [comment]
@TomTheHero The file you got from me on https://github.com/Aquerr/EagleFactions/issues/59 contains this node as well (it blocks home command only right now)

**Comment by Aquerr** [comment]
Fixed in the latest commit https://github.com/Aquerr/EagleFactions/commit/7fcc3a9a50d7872dd0c7ad9ab042acc996eb9868

This feature will be available in the next release of Eagle Factions :)
