### ISSUE TITLE
Duplicating blocks while using tools from Project E near claim

### ISSUE THREAD

**Issue by Aquerr** [Aquerr/EagleFactions#65]
## Environment

* **Sponge Version:** 1.12.2

* **Plugin Version:** 0.9.12

## What happens?

Tools from Project E duplicate blocks while using them near claim.

## Expected result

It shouldn't work that way. We should try to block this in some way.

**Comment by Aquerr** [comment]
Going to give it a try again this week.

**Comment by Kittycraft** [comment]
I have no idea if this would work, but maybe when doing onBlockBreak specify order=EARLY. I'm not sure how I could test this my self but my guess is that factions gets the event after project E does. So I'm guessing that by the time factions attempts to cancel the event, project E has already finished bundling the items into that black circle thing (I forget what its called) and they can no longer be destroyed. Maybe this would inform it otherwise?

The only other thing I can think of is going lower level and making a forge specific version of this plugin.

**Comment by Aquerr** [comment]
I think I was testing this with order=EARLY and that didn't help.

I am also thinking about checking DropItemEvent. I know there are no blocks that are dropped but it may be worth checking.
