### ISSUE TITLE
Lag from PlayerMove Listener

### ISSUE THREAD

**Issue by prodkid** [Aquerr/EagleFactions#7]
Looks like there's an lag issue, heres my timing report
https://timings.aikar.co/?id=a16733bc6d6b4879a80b086463e7c57e

**Comment by Aquerr** [comment]
I will try to fix this until the next release.

I knew there was a problem with this... or at least I thought there may be a problem.

I will need to rewrite the PlayerMoveListener and I hope it will work better next time.

Thanks for reporting!
Regards

**Comment by Aquerr** [comment]
Strange thing, it looks like it should be Ok.

Looks like you are using Animania and Modern Warfare. I think that report should not really mean that there is a problem in Eagle Factions.

I can see that PlayerMoveListener is invoked only when players are moving and so should it be.

In the report I found that around 100ms tick lag happened because of  ModerWarfare’s smoke granade.

But anyway... I will download these mods test them again with my plugin.
I need to check if PlayerMoveEvent is working properly.

**Comment by Aquerr** [comment]
I have tested it a lot and can’t find any issue.

Could you please test it again using the newest release?

Regards
