### ISSUE TITLE
Urgent: Faction /home teleporting players into ground

### ISSUE THREAD

**Issue by NGSquirrely** [Aquerr/EagleFactions#91]
## Environment

* **Sponge Version:** <Latest>

* **Plugin Version:** <Latest>

## What happens?

<player uses /f home, player is teleported beneath location and suffocates. >

## Expected result

<....>

## More information

<If you want to inform about something more then write it here.>

**Comment by Aquerr** [comment]
Provide a version you are using otherwise I will not be able to help.

Home Command should work fine always as you are specifing the home by marking a block you are standing at. Don't know how it is possible for players to teleport below the block if correct Y value (height) is set while using SetHome Command. Check your faction's home location in the file and see if the block height is right. It is the second value in the parentheses in the home node (if you are using HOCON storage).
